apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-demo
spec:
  containers:
  - name: app
    image: busybox:1.28
    command: ['sh', '-c', 'ls /etc/config && cat /etc/config/log_level && sleep 3600']
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
  volumes:
  - name: config-vol
    configMap:
      name: app-config
