apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: quota-demo
spec:
  hard:
    pods: "5"
    configmaps: "3"
    secrets: "5"
    services: "3"
    services.loadbalancers: "1"
    services.nodeports: "2"
    persistentvolumeclaims: "2"
    count/deployments.apps: "2"
    count/cronjobs.batch: "1"
