apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: default
  annotations:
    kubevirt.io/storage.contentType: "kubevirt"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

