apiVersion: v1
kind: Pod
metadata:
  name: named-port-pod
  labels:
    app: named-port-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: named-port-service
spec:
  selector:
    app: named-port-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-web
