apiVersion: v1                                                            
kind: ConfigMap                                                           
metadata:                                                                 
  name: finalizer-demo                                                    
data:                                                                     
  purpose: "demonstrating finalizers"  
