apiVersion: apps/v1                                                       
kind: Deployment                                                          
metadata:                                                                 
  name: owner-demo                                                        
spec:                                                                     
  replicas: 2                                                             
  selector:                                                               
    matchLabels:                                                          
      app: owner-demo                                                     
  template:                                                               
    metadata:                                                             
      labels:                                                             
        app: owner-demo                                                   
    spec:                                                                 
      containers:                                                         
        - name: nginx                                                     
          image: nginx:1.27 
