apiVersion: v1                                                            
kind: Service                                                             
metadata:                                                                 
  name: web-app                                                           
  labels:                                                                 
    app.kubernetes.io/name: web-app                                       
    app.kubernetes.io/instance: web-app-001                               
    app.kubernetes.io/version: "1.0.0"                                    
    app.kubernetes.io/component: server                                   
    app.kubernetes.io/managed-by: kubectl                                 
spec:                                                                     
  selector:                                                               
    app.kubernetes.io/name: web-app                                       
    app.kubernetes.io/instance: web-app-001                               
  ports:                                                                  
  - port: 80                                                              
    targetPort: 80   
