apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
    - name: demo
      image: busybox
      command: ["sh", "-c", "cat /config/game.properties && sleep 3600"]
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: game-demo
  restartPolicy: Never

